// <auto-generated />
namespace BtcProApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Register_Table_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Register_Table_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201707120323404_Register_Table_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
