// <auto-generated />
namespace BtcProApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Member_addfields_AchievementDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Member_addfields_AchievementDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201707021330272_Member_addfields_AchievementDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
